/**
 * @license
 * Copyright 2021 Google LLC. All Rights Reserved.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * =============================================================================
 */

// This file is autogenerated.


import {registerKernel} from '@tensorflow/tfjs-core/dist/base';
import '@tensorflow/tfjs-core/dist/base_side_effects';
export * from '@tensorflow/tfjs-core/dist/base';
export * from '@tensorflow/tfjs-converter';

//backend = webgl
export * from '@tensorflow/tfjs-backend-webgl/dist/base';
import {fromPixelsConfig as FromPixels_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FromPixels';
registerKernel(FromPixels_webgl);
import {castConfig as Cast_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Cast';
registerKernel(Cast_webgl);
import {expandDimsConfig as ExpandDims_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/ExpandDims';
registerKernel(ExpandDims_webgl);
import {resizeBilinearConfig as ResizeBilinear_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/ResizeBilinear';
registerKernel(ResizeBilinear_webgl);
import {realDivConfig as RealDiv_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/RealDiv';
registerKernel(RealDiv_webgl);
import {subConfig as Sub_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Sub';
registerKernel(Sub_webgl);
import {multiplyConfig as Multiply_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Multiply';
registerKernel(Multiply_webgl);
import {fusedConv2DConfig as FusedConv2D_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/FusedConv2D';
registerKernel(FusedConv2D_webgl);
import {depthwiseConv2dNativeConfig as DepthwiseConv2dNative_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/DepthwiseConv2dNative';
registerKernel(DepthwiseConv2dNative_webgl);
import {addConfig as Add_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Add';
registerKernel(Add_webgl);
import {reluConfig as Relu_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Relu';
registerKernel(Relu_webgl);
import {padV2Config as PadV2_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/PadV2';
registerKernel(PadV2_webgl);
import {maxPoolConfig as MaxPool_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/MaxPool';
registerKernel(MaxPool_webgl);
import {stridedSliceConfig as StridedSlice_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/StridedSlice';
registerKernel(StridedSlice_webgl);
import {reshapeConfig as Reshape_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Reshape';
registerKernel(Reshape_webgl);
import {packConfig as Pack_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Pack';
registerKernel(Pack_webgl);
import {concatConfig as Concat_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Concat';
registerKernel(Concat_webgl);
import {identityConfig as Identity_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Identity';
registerKernel(Identity_webgl);
import {sliceConfig as Slice_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Slice';
registerKernel(Slice_webgl);
import {sigmoidConfig as Sigmoid_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/Sigmoid';
registerKernel(Sigmoid_webgl);
import {nonMaxSuppressionV3Config as NonMaxSuppressionV3_webgl} from '@tensorflow/tfjs-backend-webgl/dist/kernels/NonMaxSuppressionV3';
registerKernel(NonMaxSuppressionV3_webgl);